// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'About the Project',
      collapsed: false,
      items: [
        'intro',
        'framework',
        'ecosystem-overview',
        'repository-map',
      ],
    },
    {
      type: 'category',
      label: 'Using the Curricula',
      collapsed: false,
      items: [
        'using-the-curricula',
        'implementation-pathways',
        'curriculum-adoption-checklist',
        'ecosystem-skills-overview',
      ],
    },
    {
      type: 'category',
      label: 'For Facilitators',
      collapsed: false,
      items: [
        'privacy-and-student-data',
        'interactive-activity-specs',
      ],
    },
    {
      type: 'category',
      label: 'Shared Toolkits',
      collapsed: false,
      link: {type: 'doc', id: 'toolkits/shared-toolkits-intro'},
      items: [
        'toolkits/shared-toolkits-intro',
        'toolkits/shared-toolkit-printables',
        {
          type: 'category',
          label: 'Coping Skills Toolkit',
          collapsed: true,
          link: {type: 'doc', id: 'toolkits/coping-skills/coping-skills-intro'},
          items: [
            'toolkits/coping-skills/coping-skills-intro',
            'toolkits/coping-skills/coping-lesson-01-system-signals',
            'toolkits/coping-skills/coping-lesson-02-pause-button',
            'toolkits/coping-skills/coping-lesson-03-grounding',
            'toolkits/coping-skills/coping-lesson-04-breathing',
            'toolkits/coping-skills/coping-lesson-05-body-reset',
            'toolkits/coping-skills/coping-lesson-06-thought-bugs',
            'toolkits/coping-skills/coping-lesson-07-asking-for-help',
            'toolkits/coping-skills/coping-lesson-08-coping-menu',
            'toolkits/coping-skills/coping-printables',
          ],
        },
        {
          type: 'category',
          label: 'Communication Toolkit',
          collapsed: true,
          link: {type: 'doc', id: 'toolkits/communication/communication-intro'},
          items: [
            'toolkits/communication/communication-intro',
            'toolkits/communication/communication-lesson-01-listening-is-active',
            'toolkits/communication/communication-lesson-02-clarifying-questions',
            'toolkits/communication/communication-lesson-03-explain-your-thinking',
            'toolkits/communication/communication-lesson-04-disagree-without-attacking',
            'toolkits/communication/communication-lesson-05-ask-for-help',
            'toolkits/communication/communication-lesson-06-feedback-is-information',
            'toolkits/communication/communication-lesson-07-repair-after-misunderstanding',
            'toolkits/communication/communication-lesson-08-build-your-communication-toolbox',
            'toolkits/communication/communication-printables',
          ],
        },
        {
          type: 'category',
          label: 'Problem Solving Toolkit',
          collapsed: true,
          link: {type: 'doc', id: 'toolkits/problem-solving/problem-solving-intro'},
          items: [
            'toolkits/problem-solving/problem-solving-intro',
            'toolkits/problem-solving/problem-solving-lesson-01-what-problem',
            'toolkits/problem-solving/problem-solving-lesson-02-facts-guesses-missing',
            'toolkits/problem-solving/problem-solving-lesson-03-break-into-parts',
            'toolkits/problem-solving/problem-solving-lesson-04-brainstorm-options',
            'toolkits/problem-solving/problem-solving-lesson-05-safe-step',
            'toolkits/problem-solving/problem-solving-lesson-06-observe',
            'toolkits/problem-solving/problem-solving-lesson-07-adjust',
            'toolkits/problem-solving/problem-solving-lesson-08-checklist',
            'toolkits/problem-solving/problem-solving-printables',
          ],
        },
        {
          type: 'category',
          label: 'Learning How to Learn Toolkit',
          collapsed: true,
          link: {type: 'doc', id: 'toolkits/learning-how-to-learn/learning-how-to-learn-intro'},
          items: [
            'toolkits/learning-how-to-learn/learning-how-to-learn-intro',
            'toolkits/learning-how-to-learn/learning-lesson-01-forgetting-is-normal',
            'toolkits/learning-how-to-learn/learning-lesson-02-practice-beats-rereading',
            'toolkits/learning-how-to-learn/learning-lesson-03-small-practice-over-time',
            'toolkits/learning-how-to-learn/learning-lesson-04-mistakes-are-data',
            'toolkits/learning-how-to-learn/learning-lesson-05-teach-it-to-learn-it',
            'toolkits/learning-how-to-learn/learning-lesson-06-better-learning-questions',
            'toolkits/learning-how-to-learn/learning-lesson-07-practice-plan',
            'toolkits/learning-how-to-learn/learning-lesson-08-learning-toolbox',
            'toolkits/learning-how-to-learn/learning-printables',
          ],
        },
        {
          type: 'category',
          label: 'Executive Function Toolkit',
          collapsed: true,
          link: {type: 'doc', id: 'toolkits/executive-function/executive-function-intro'},
          items: [
            'toolkits/executive-function/executive-function-intro',
            'toolkits/executive-function/executive-function-lesson-01-what-is-the-job',
            'toolkits/executive-function/executive-function-lesson-02-first-step-tiny',
            'toolkits/executive-function/executive-function-lesson-03-checklist',
            'toolkits/executive-function/executive-function-lesson-04-time-energy',
            'toolkits/executive-function/executive-function-lesson-05-prioritize',
            'toolkits/executive-function/executive-function-lesson-06-distractions',
            'toolkits/executive-function/executive-function-lesson-07-recover-interruptions',
            'toolkits/executive-function/executive-function-lesson-08-start-finish-plan',
            'toolkits/executive-function/executive-function-printables',
          ],
        },
        {
          type: 'category',
          label: 'Collaboration Toolkit',
          collapsed: true,
          link: {type: 'doc', id: 'toolkits/collaboration/collaboration-intro'},
          items: [
            'toolkits/collaboration/collaboration-intro',
            'toolkits/collaboration/collaboration-lesson-01-making-together',
            'toolkits/collaboration/collaboration-lesson-02-roles-visible',
            'toolkits/collaboration/collaboration-lesson-03-share-work-fairly',
            'toolkits/collaboration/collaboration-lesson-04-check-in',
            'toolkits/collaboration/collaboration-lesson-05-disagree-build',
            'toolkits/collaboration/collaboration-lesson-06-repair',
            'toolkits/collaboration/collaboration-lesson-07-finish-together',
            'toolkits/collaboration/collaboration-lesson-08-collaboration-plan',
            'toolkits/collaboration/collaboration-printables',
          ],
        },
        {
          type: 'category',
          label: 'Information Organization Toolkit',
          collapsed: true,
          link: {type: 'doc', id: 'toolkits/information-organization/information-organization-intro'},
          items: [
            'toolkits/information-organization/information-organization-intro',
            'toolkits/information-organization/information-organization-lesson-01-sort',
            'toolkits/information-organization/information-organization-lesson-02-categories',
            'toolkits/information-organization/information-organization-lesson-03-labels',
            'toolkits/information-organization/information-organization-lesson-04-examples',
            'toolkits/information-organization/information-organization-lesson-05-notes',
            'toolkits/information-organization/information-organization-lesson-06-maps-diagrams-timelines',
            'toolkits/information-organization/information-organization-lesson-07-sources-evidence',
            'toolkits/information-organization/information-organization-lesson-08-information-system',
            'toolkits/information-organization/information-organization-printables',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: false,
      items: [
        'contributor-guide',
        'content-style-guide',
        'technical-style-guide',
        'accessibility-notes',
      ],
    },
    {
      type: 'category',
      label: 'Open Source',
      collapsed: false,
      items: [
        'open-source',
      ],
    },
  ],
};

export default sidebars;
